---
- name: setup webserver
  hosts: all
  become: true
  become_user: root
  tasks:
    - name: httpd installed
      ansible.builtin.yum:
        name: httpd
        state: latest

    - name: custom index.html
      ansible.builtin.copy:
        dest: /var/www/html/index.html
        content: "{{ custom.content }}"

    - name: httpd service enabled
      ansible.builtin.service:
        name: httpd
        enabled: true
        state: started

    #- name: open firewall
    # ansible.posix.firewalld:
    #    service: http
    #    state: enabled
    #    immediate: true
    #    permanent: true
